### ISSUE TITLE
Project not found in Management Portal

### ISSUE THREAD

**Issue by Hsankesara** [RADAR-base/RADAR-Rest-Source-Auth#238]
Radar-Rest Source Auth cannot fetch the project details from the management portal. 

![Screenshot 2023-07-26 at 15 41 54](https://github.com/RADAR-base/RADAR-Rest-Source-Auth/assets/21009715/4a70ff10-5cbd-437e-bb79-738ae73a0850)

**Comment by mpgxvii** [comment]
When getting users from `radar-jersey`, it returns `project_not_found` error:
```
ERROR - [404] GET projects/STAGING_PROJECT/users - project_not_found: Project STAGING_PROJECT not found in Management Portal. (HttpApplicationExceptionMapper.kt:30)
```
This is caused by using the old MP (before MP2.0). The old MP doesn't have the organization structure, so when checking permissions of the user for the project, it fails. This is because it checks the organization first then if the organization is null, it just says the project does not exist. From here: https://github.com/RADAR-base/radar-jersey/blob/main/radar-jersey/src/main/kotlin/org/radarbase/jersey/auth/filter/PermissionFilter.kt#L88
